FROM centos:7
ENV container docker

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done);\
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

CMD ["/usr/sbin/init"]


RUN mkdir -p /var/log/ap/dev/
ADD docker7/rsyslog.conf /etc/rsyslog.conf

ARG INSTALL_DIR=/var/ap/install
RUN mkdir -p $INSTALL_DIR/
ADD ws/requirements/* $INSTALL_DIR/
ADD docker7/yum_install.sh $INSTALL_DIR
RUN $INSTALL_DIR/yum_install.sh

ARG APP_DIR=/var/ap/ws
RUN mkdir -p $APP_DIR
WORKDIR $APP_DIR
