version: '3'
services:
  web:
    env_file: ./docker7/web/web.env
    build:
      context: .
      dockerfile: ./Dockerfile-web
    privileged: true
    ports:
      - "8000:8000"
    volumes:
      - .:/var/apt/dev/release
      - ./config:/var/apt/dev/config
    depends_on:
      - db
    links:
      - db:db
      - ldap:ldap

  db:
    image: mysql:5.6
    env_file: ./docker7/db/mysql.env
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker7/db/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - "3306:3306"

  ldap:
    image: dinkel/openldap
    env_file: ./docker7/ldap/ldap.env
    ports:
      - "389:389"

  ldapadmin:
    image: osixia/phpldapadmin:0.6.12
    env_file: ./docker7/ldap/ldapadmin.env
    ports:
      - "1234:80"
      - "6443:443"
    links:
      - ldap:ldap-host


volumes:
  mysqldata:
    external: true
