FROM centos:7
ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done);\
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
CMD ["/usr/sbin/init"]

RUN mkdir -p /var/log/ap/dev/
ADD docker7/web/rsyslog.conf /etc/rsyslog.conf

ARG INSTALL_DIR=/var/apt/install
RUN mkdir -p $INSTALL_DIR/
ADD requirements/* $INSTALL_DIR/
ADD docker7/yum_install.sh $INSTALL_DIR
RUN $INSTALL_DIR/yum_install.sh

RUN mkdir -p /var/apt/dev/config

ARG APP_DIR=/var/apt/dev/release
RUN mkdir -p $APP_DIR
WORKDIR $APP_DIR
