FROM centos:7
ENV container docker

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done);\
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

CMD ["/usr/sbin/init"]

#RUN yum -y install epel-release
#RUN yum -y update
#RUN yum -y install python-pip

#RUN yum -y clean all

ARG APP_DIR_CONT
ARG REQ_DIR_HOST
ARG REQ_DIR_CONT=../requirements/

RUN mkdir -p $APP_DIR_CONT
WORKDIR $APP_DIR_CONT

RUN mkdir -p $REQ_DIR_CONT

COPY ../ws/requirements/base.txt /var/ap/requirements/


#RUN pip install --upgrade pip
#RUN pip install -r ../requirements/base.txt