FROM centos:7
ENV container docker

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done);\
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

CMD ["/usr/sbin/init"]


RUN mkdir -p /var/log/ap/dev/
ADD requirements/rsyslog.conf /etc/rsyslog.conf
#ADD requirements/rsyslog_ap.conf /etc/rsyslog.d/rsyslog_ap.conf

RUN mkdir -p /var/ap/requirements
ADD requirements/* /var/ap/requirements/
RUN /var/ap/requirements/yum_install.sh

ARG APP_DIR_CONT
RUN mkdir -p $APP_DIR_CONT
WORKDIR $APP_DIR_CONT

# CMD python manage.py runserver 0.0.0.0:8000
